name: CI

on:
  pull_request:
    branches:
      - main
      
jobs:
  build-and-test:
    runs-on: ubuntu-latest

    env:
      CONFIGURATION: ${{ secrets.CONFIGURATION || 'Release' }}
      SOLUTION: ./src/Purview.Telemetry.SourceGenerator.slnx

    steps:
      - name: Checkout code
        uses: actions/checkout@v3

      - name: Set up .NET
        uses: actions/setup-dotnet@v3
        with:
          global-json-file: ./src/global.json

      - name: Install dependencies
        run: dotnet restore ${{ env.SOLUTION }}

      - name: Build
        run: dotnet build ${{ env.SOLUTION }} --no-restore --configuration ${{ env.CONFIGURATION }}

      - name: Run tests
        run: dotnet test ${{ env.SOLUTION }} --no-build --verbosity normal --configuration ${{ env.CONFIGURATION }}
      
